language: python
python:
  - "3.5"
install:
  - pip install pytest coverage pytest-timeout pytest_socket
  - pip install python-coveralls
  - pip install --upgrade coverage
  - pip install .
  - cp ./tests/.pubrunner.settings.yml ./
# command to run tests
script:
  - coverage --version
  - python --version
  - coverage run --branch -m pytest -v && coverage report -m
after_success:
  - coveralls
