language: python
python:
  - "3.6"
install:
  - pip install pytest coverage 
  - pip install python-coveralls
  - pip install --upgrade coverage
  - pip install .
  - wget ftp://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_package/9b/35/PMC5199186.tar.gz
# command to run tests
script:
  - coverage --version
  - python --version
  - coverage run --branch -m pytest -v && coverage report -m
after_success:
  - coveralls
