name: CountWords
version: 0.2
mode: complete
resources:
   all:
      - FOODON
   main:
      - PUBMED
   test:
      - PUBMED_TWOFILES:
         rename: PUBMED
run:
   - python CountWords.py -i {IN:PUBMED} -o {OUT:OUTPUTDIR}
output: OUTPUTDIR
