name: CountWords
version: 0.2
mode: complete
resources:
   all:
      - FOODON
   main:
      - PUBMED:
         name: PUBMED
   test:
      - PUBMED_TWOFILES:
         name: PUBMED
run:
   - python CountWords.py -i {PUBMED} -o {OUTPUTDIR}
output: OUTPUTDIR
